app:
  watchdir: c:\\temp\\watchdir


# ロガー設定
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.batch: INFO
    org.springframework.jdbc: INFO
    com.atomikos.jdbc: INFO
    org.springframework.transaction: INFO

# Springの設定
spring:
  main:
    banner-mode: "off"
  batch:
    initialize-schema: NEVER
    job:
      enabled: false
  resource:
    chain:
      enable: true
  # データソースの設定（ローカルトランザクション用）
  jta:
    # JTAを有効にする
    enabled: true
    transaction_manager_id: 192.168.100.14.atomikos.tm
    # Atomikos固有の設定
    atomikos:
      properties:
        # AtomikosProperties.java への設定値(jta.propertiesに設定した場合と値構成が異なっています)
        # (note) 下記の値はデフォルト値と同じです
        max_timeout: 300000
        default_jta_timeout: 10000
        max_actives: 50
        enable_logging: true
        serial_jta_transactions: true
        allow_subtransactions: true
        force_shutdown_on_vm_exit: false
        default_max_wait_time_on_shutdown: 9223372036854775807
        log_base_name: tmlog
        checkpoint_interval: 500
        # threaded_2pc の設定値
        threaded_two_phase_commit: false
        #        # (note) この値はPGでspring.jta.transaction_manager_idで上書きしますので設定しても無駄です
        #        tm_unique_name: 192.168.100.14.atomikos.tm
        #        # (note)この値はPGで組み立てるため設定しても無駄です
        #        log_base_dir: /xxx/transaction-logs
        # 回復オプション
        recovery:
          forget_orphaned_log_entries_delay: 86400000
          # recovery_delay の設定値
          delay: 10001
          # oltp_max_retries の設定値
          max_retries: 5
          # oltp_retry_interval の設定値
          retry_interval: 10000
      datasource:
        # XA用DataSourceの定義(1個目)
        ora:
          # AbstractDataSourceBean の設定値
          # (note) unique-resource-name, test-quer,max-life-timey, default-isolation-level以外はデフォルト値
          unique-resource-name: XaDb1DataSource
          max-pool-size: 5
          min-pool-size: 1
          borrow-connection-timeout: 30
          reap-timeout: 0
          max-idle-time: 60
          test-query: select 1 from dual
          maintenance-interval: 60
          login-timeout: 0
          max-life-time: 20000
          # TRANSACTION_READ_COMMITTED
          default-isolation-level: 2
          enable-concurrent-connection-validation: true
          # AtomikosDataSourceBean の設定値
          # (note) OracleXA用DataSource実装クラスを指定する
          xa-data-source-class-name: oracle.jdbc.xa.client.OracleXADataSource
          # xa-data-source-class-nameが示す実装クラスに引き渡すプロパティ.実装クラス依存の値になる
          xa-properties:
            URL: jdbc:oracle:thin:@//localhost:1521/xepdb1
            user: MYTEST
            password: MYTEST
# MyBatis設定
mybatis:
  configuration:
    default-fetch-size: 10
    default-statement-timeout: 30


